FROM mcr.microsoft.com/dotnet/aspnet:6.0.1-bullseye-slim AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0.101-bullseye-slim AS build
WORKDIR /src
COPY ["WebApiGraphQl/", "WebApiGraphQl/"]

RUN dotnet restore "WebApiGraphQl/WebApiGraphQl.csproj"
RUN dotnet build "WebApiGraphQl/WebApiGraphQl.csproj" -c Relase -o /app/build

FROM build AS publish
RUN dotnet publish "WebApiGraphQl/WebApiGraphQl.csproj" -c Relase -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "WebApiGraphQl.dll"]