FROM mcr.microsoft.com/dotnet/sdk:5.0-buster-slim AS build-env
WORKDIR /src

# copy csproj and restore as distinct layers
RUN mkdir FansApp

COPY FansApp/FansApp.csproj ./FansApp/FansApp.csproj

WORKDIR /src/FansApp
RUN dotnet restore

WORKDIR /src

# copy everything else and build app
COPY FansApp/. ./FansApp/
WORKDIR /src/FansApp
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:5.0-buster-slim

WORKDIR /app

COPY --from=build-env /src/FansApp/out .

EXPOSE 80
ENTRYPOINT ["dotnet", "FansApp.dll"]