FROM mcr.microsoft.com/dotnet/aspnet:5.0-buster-slim AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:5.0-buster-slim AS build
WORKDIR /src
COPY ["TutoRenderFragement/TutoRenderFragement.csproj", "TutoRenderFragement/"]
RUN dotnet restore "TutoRenderFragement/TutoRenderFragement.csproj"
COPY . .
WORKDIR "/src/TutoRenderFragement"
RUN dotnet build "TutoRenderFragement.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "TutoRenderFragement.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "TutoRenderFragement.dll"]