// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiCodeFirst.Data;

#nullable disable

namespace WebApiCodeFirst.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220129111929_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("WebApiCodeFirst.Models.Adresse", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.ToTable("Adresses");
                });

            modelBuilder.Entity("WebApiCodeFirst.Models.Client", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("WebApiCodeFirst.Models.Commande", b =>
                {
                    b.Property<string>("IdCmd")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdCmd");

                    b.ToTable("Commandes");
                });

            modelBuilder.Entity("WebApiCodeFirst.Models.Panier", b =>
                {
                    b.Property<Guid>("IdPanier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CommandeIdCmd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IdItem")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantite")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdPanier");

                    b.HasIndex("CommandeIdCmd");

                    b.ToTable("Paniers");
                });

            modelBuilder.Entity("WebApiCodeFirst.Models.Telephone", b =>
                {
                    b.Property<string>("Number")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Number");

                    b.HasIndex("ClientId");

                    b.ToTable("Telephones");
                });

            modelBuilder.Entity("WebApiCodeFirst.Models.Adresse", b =>
                {
                    b.HasOne("WebApiCodeFirst.Models.Client", null)
                        .WithOne("Adresse")
                        .HasForeignKey("WebApiCodeFirst.Models.Adresse", "ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApiCodeFirst.Models.Panier", b =>
                {
                    b.HasOne("WebApiCodeFirst.Models.Commande", null)
                        .WithMany("Panier")
                        .HasForeignKey("CommandeIdCmd")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApiCodeFirst.Models.Telephone", b =>
                {
                    b.HasOne("WebApiCodeFirst.Models.Client", null)
                        .WithMany("Telephones")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApiCodeFirst.Models.Client", b =>
                {
                    b.Navigation("Adresse")
                        .IsRequired();

                    b.Navigation("Telephones");
                });

            modelBuilder.Entity("WebApiCodeFirst.Models.Commande", b =>
                {
                    b.Navigation("Panier");
                });
#pragma warning restore 612, 618
        }
    }
}
